# Generated by Django 3.1 on 2024-04-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_avaible',
            new_name='is_available',
        ),
    ]
